# Allowed devices indexes for sys devices others wil be ignored
# You have to provide here idexes of devices from /sys/class/hwmon to use
# Empty value will skip auto detection, and [[propellers]] section would not work
#idx=[0,1,5]

# Allowed nvidia GPUS
# Other will be ignored
nv_idx=[0,1,5]

#FAN speed in percents
pwm_ok = 60 # Default fan speed for all propellers
#pwm_min = 0 # Optional
#pwm_max = 100 # Optional

# Default temperature settings
temp_ok = 65
temp_hot = 75
temp_crit = 85


# Additional properties for autodetected devices
# Would override default settings
[[propellers]]
idx = [0,3] # Required value - indexes of devices you want apply this settings to
type = "nv" #for Nvidia devices or, if not provided, system device indexes will be used
pwm_ok = 70
temp_ok=69

[[propellers]]
idx = [1,2]
pwm_ok = 120
pwm_min = 10
temp_ok = 56
temp_hot = 60


# Custom devices you can create as many as you like
# this devices may have custom temperature inputs and pwm files
[[devices]]
name="Device Name"
# Absolute path to PWM file
pwm_file="/sys/class/hwmon/hwmon33/pwm2"
pwm_ok = 75

# Max temperature will be used as trigger to increase PWM
# AVG for last N rounds will be used to decrease PWM
# Absolute paths to temp*_input files to watch
#sys_temp_input=['/sys/class/hwmon/hwmon0/temp1_input', '/sys/class/hwmon/hwmon1/temp2_input']
# Int ID of Nvidia devices to watch temperature
#nv_temp_input=[1,2]



